# Generated by Django 4.0 on 2021-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Our_business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(blank=True, default='default.jpg', upload_to='background/')),
                ('about', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'Our_business',
                'db_table': 'Our_business',
            },
        ),
    ]
