# Generated by Django 4.0 on 2021-12-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_business',
            name='FacebookUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_business',
            name='InstragramUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_business',
            name='LinkedInUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_business',
            name='TwitterUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_business',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_business',
            name='address',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='our_business',
            name='mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
