# Generated by Django 4.0 on 2021-12-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_our_business_facebookurl_our_business_instragramurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_business',
            name='business_category',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
