# Generated by Django 4.0 on 2022-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_our_business_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_business',
            name='sub_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
