# Generated by Django 4.0 on 2022-01-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_our_business_sub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sub_name', models.CharField(blank=True, max_length=160, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(blank=True, default='default.jpg', upload_to='background/')),
                ('about', models.CharField(max_length=160)),
                ('company', models.CharField(max_length=160)),
                ('Product_category', models.CharField(blank=True, max_length=160, null=True)),
                ('Link', models.URLField(blank=True, null=True)),
                ('mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name': 'Our_products',
                'db_table': 'Our_products',
            },
        ),
    ]
