# Generated by Django 4.0 on 2022-01-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_our_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_products',
            name='producttype',
            field=models.CharField(blank=True, choices=[('Digital Product', 'Digital Product'), ('Digital Service', 'Digital Service'), ('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=160, null=True),
        ),
    ]
