# Generated by Django 4.0 on 2022-01-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_our_products_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_products',
            name='img',
            field=models.ImageField(blank=True, default='img/default.jpg', upload_to='background/'),
        ),
    ]
