# Generated by Django 4.0 on 2022-01-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_our_products_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(blank=True, default='default.jpg', upload_to='background/')),
                ('about', models.CharField(max_length=160)),
                ('Website', models.URLField(blank=True, null=True)),
                ('FacebookUrl', models.URLField(blank=True, null=True)),
                ('TwitterUrl', models.URLField(blank=True, null=True)),
                ('LinkedInUrl', models.URLField(blank=True, null=True)),
                ('InstragramUrl', models.URLField(blank=True, null=True)),
                ('mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name': 'Our_Team',
                'db_table': 'Our_Team',
            },
        ),
    ]
